spring:
  application:
    name: gig-service
  datasource:
    url: jdbc:postgresql://localhost:5433/gig_db
    username: postgres
    password: "password"
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

services:
  auth-service:
    url: ${SERVICES_AUTH_SERVICE_URL:http://localhost:8082}
  internal-secret: ${INTERNAL_SERVICES_SECRET:dev_internal_secret_key_123!}


