server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

jwt:
  secret: ${JWT_SECRET}

services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8082}
  gig-service:
    url: ${GIG_SERVICE_URL:http://localhost:8081}
  order-service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG